export const customPromptLanguages = [
  "Default language",
  "Deutsch",
  "English",
  "Español",
  "Français",
  "Italiano",
  "Português",
  "Polski",
  "Українська",
  "Af Soomaali",
  "Afrikaans",
  "Azərbaycan dili",
  "Bahasa Indonesia",
  "Bahasa Malaysia",
  "Bahasa Melayu",
  "Basa Jawa",
  "Basa Sunda",
  "Bosanski jezik",
  "Català",
  "Čeština",
  "Chichewa",
  "Cymraeg",
  "Dansk",
  "Deutsch",
  "Eesti keel",
  "English",
  "English (UK)",
  "English (US)",
  "Español",
  "Esperanto",
  "Euskara",
  "Français",
  "Gaeilge",
  "Galego",
  "Hrvatski jezik",
  "isiXhosa",
  "isiZulu",
  "Íslenska",
  "Italiano",
  "Kiswahili",
  "Kreyòl Ayisyen",
  "Kurdî",
  "Latīna",
  "Latviešu valoda",
  "Lëtzebuergesch",
  "Lietuvių kalba",
  "Magyar",
  "Malagasy",
  "Malti",
  "Māori",
  "Nederlands",
  "Norsk",
  "O'zbek tili",
  "Polski",
  "Português",
  "Română",
  "Sesotho",
  "Shqip",
  "Slovenčina",
  "Slovenščina",
  "Suomi",
  "Svenska",
  "Tagalog",
  "Tatarça",
  "Türkçe",
  "Việt ngữ",
  "Yorùbá",
  "Ελληνικά",
  "Беларуская мова",
  "Български език",
  "Кыр",
  "Қазақ тілі",
  "Македонски јазик",
  "Монгол хэл",
  "Русский",
  "Српски језик",
  "Тоҷикӣ",
  "Українська",
  "ქართული",
  "Հայերեն",
  "ייִדיש",
  "עברית",
  "ئۇيغۇرچە",
  "اردو",
  "العربية",
  "پښتو",
  "فارسی",
  "नेपाली",
  "मराठी",
  "हिन्दी",
  "বাংলা",
  "ਪੰਜਾਬੀ",
  "ગુજરાતી",
  "ଓଡ଼ିଆ",
  "தமிழ்",
  "తెలుగు",
  "ಕನ್ನಡ",
  "മലയാളം",
  "සිංහල",
  "ไทย",
  "ພາສາລາວ",
  "ဗမာစာ",
  "ភាសាខ្មែរ",
  "한국어",
  "中文",
  "繁體中文",
  "日本語"
];

export const customPromptTones = [
  "Default",
  "Authoritative",
  "Clinical",
  "Cold",
  "Confident",
  "Cynical",
  "Emotional",
  "Empathetic",
  "Formal",
  "Friendly",
  "Humorous",
  "Informal",
  "Ironic",
  "Optimistic",
  "Pessimistic",
  "Playful",
  "Sarcastic",
  "Serious",
  "Sympathetic",
  "Tentative",
  "Warm"
];

export const customPromptStyles = [
  "Default",
  "Academic",
  "Analytical",
  "Argumentative",
  "Conversational",
  "Creative",
  "Critical",
  "Descriptive",
  "Epigrammatic",
  "Epistolary",
  "Expository",
  "Informative",
  "Instructive",
  "Journalistic",
  "Metaphorical",
  "Narrative",
  "Persuasive",
  "Poetic",
  "Satirical",
  "Technical"
];
